---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    package:
     name:
      - htop
      - terminator
      - virtualbox
      - vim-nox
      - tmux

