---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    package:
     name:
      - htop
      - terminator
      - vim-nox
      - tmux
  - name: Install ULauncher Process
    block:
      - name: Add repository ULauncher -> ppa:agornostal/ulauncher
        apt_repository:
          repo: ppa:agornostal/ulauncher
          codename: trusty
      - name: Install ULauncher Package
        package:
          name: ulauncher
