---
- hosts: localhost
  connection: local
  become: true
  roles:
    - base
    - albert
    - role: keyboard-configuration
      keyboard_model: pc105
      keyboard_layout: es
      keyboard_variant: dvorak
      #   - nvim
      #- custom_bash
      #- terminator
    - keyboard_shortcuts
