---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    package:
     name:
      - htop
      - terminator
      - vim-nox
      - tmux
  - name: Install ULauncher Process
    block:
      - name: Add GPG key
        apt_key:
          keyserver: keyserver.ubuntu.com
          id: 0xfaf1020699503176
          keyring: /usr/share/keyrings/ulauncher-archive-keyring.gpg

      - name: Add repository ULauncher -> ppa:agornostal/ulauncher
        apt_repository:
          repo: "deb [signed-by=/usr/share/keyrings/ulauncher-archive-keyring.gpg] http://ppa.launchpad.net/agornostal/ulauncher/ubuntu jammy main"
          state: present
          filename: ulauncher-jammy
          update_cache: yes
