---
- name: Download Node script
  get_url:
    url: https://deb.nodesource.com/setup_23.x
    dest: /tmp/nodesource_setup.sh 
    mode: '0755'

- name: Execute script nodesource_setup.sh 
  shell: /tmp/nodesource_setup.sh
  args:
    executable: /bin/bash

- name: Update repositories
  apt:
    update_cache: yes

- name: Install nodejs
  package:
    name: nodejs
    state: present

- name: Configure npm
  block:
    - name: Configure npm user global directory
      command: "npm config set prefix '{{ npm_local_directory }}'"
      become_user: "{{ user }}"

    - name: Create bin local directory
      file:
        path: "{{ npm_local_directory }}bin/"
        group: "{{ group }}"
        owner: "{{ user }}"
        mode: "0755"
        state: directory 
