---
- name: Install packages
  package:
      name:
        - htop
        - terminator
        - vim-nox
        - tmux
        - wget
        - python3-pip
        - python3-venv
        - git
        - curl
